image: Visual Studio 2017

before_build:
  - gitversion /l console /output buildserver

build_script:
  - dotnet msbuild /t:Restore /t:Build /p:Configuration=Release /p:Version=%GitVersion_NuGetVersion%

artifacts:
  - path: '*/bin/Release/*.nupkg'

deploy:
  provider: Environment
  name: nuget.org
  on:
    appveyor_repo_tag: true
